[package]
name = "rgeocoder"
edition = "2021"
version = "0.1.3"
authors = ["Phil V. <philippe@arcadian.be>"]

[lib]
# crate-type = ["dylib"]
name = "rgeocoder"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
kdtree = "0.7.0"
quick-csv = "0.1.6"
rustc-serialize = "0.3.22"
thiserror = "1.0"