[package]
name = "rgeocoder"
version = "0.1.3"
authors = ["Phil V. <philippe@arcadian.be>"]

[lib]
# crate-type = ["dylib"]
name = "rgeocoder"
crate-type = ["cdylib"]

[dependencies]
kdtree = "0.4.0"
quick-csv = "0.1.6"
rustc-serialize = "0.3.22"
failure = "0.1.1"
pyo3 = "0.2.7"
